services:
  backend:
    build: .
    container_name: casino_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    networks:
      - casino_network

  frontend:
    image: nginx:alpine
    container_name: casino_frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - casino_network

networks:
  casino_network:
    driver: bridge